import { access, mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { createServer, type Server } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { type ResolvedConfig, resolveConfig } from "../../src/config/config-resolution.js";
import { discoverActiveRuntime } from "../../src/node/active-runtime-discovery.js";
import { ActiveRuntimeFileStore } from "../../src/node/active-runtime-file-store.js";
import { type DevDaemon, startDevDaemon } from "../../src/node/dev-daemon.js";
import { createDevProjectRuntime } from "../../src/node/dev-runtime-dependencies.js";
import { acquireStorageLock } from "../../src/node/storage-lock.js";
import { storagePaths } from "../../src/node/storage-paths.js";

const temporaryDirectories: string[] = [];
const daemons: DevDaemon[] = [];

afterEach(async () => {
	await Promise.all(daemons.splice(0).map((daemon) => daemon.close().catch(() => undefined)));
	await Promise.all(
		temporaryDirectories
			.splice(0)
			.map((directory) => rm(directory, { force: true, recursive: true })),
	);
	vi.restoreAllMocks();
});

describe("dev daemon", () => {
	it("boots a real ProjectRuntime, publishes discovery last, and leaves persistent state", async () => {
		const fixture = await fixtureConfig();
		const daemon = await startDevDaemon(
			{ cwd: fixture.project, port: 0 },
			{ loadConfig: async () => fixture.config },
		);
		daemons.push(daemon);
		const paths = storagePaths(fixture.storage);

		expect(daemon.address.port).toBeGreaterThan(0);
		expect(daemon.address.url).toBe(daemon.descriptor.url);
		expect(daemon.descriptor.configFingerprint).toBe(fixture.config.fingerprint);
		expect(daemon.connections).toEqual({ env: {}, services: {} });
		expect(daemon.environmentPath).toBe(join(fixture.storage, ".env"));
		expect(await readFile(daemon.environmentPath, "utf8")).toBe(
			"# Generated by localhost2137. Do not edit.\n",
		);
		expect((await stat(paths.controlToken)).mode & 0o777).toBe(0o600);
		expect((await stat(paths.runtime)).mode & 0o777).toBe(0o600);

		const discovered = await discoverActiveRuntime(fixture.storage);
		await expect(discovered.client.listInstances()).resolves.toEqual([
			expect.objectContaining({ id: "dev", persistence: "persistent" }),
		]);

		await daemon.close();
		await expect(daemon.close()).resolves.toBeUndefined();
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
		expect(await pathExists(daemon.environmentPath)).toBe(true);
	});

	it("rolls back the runtime and lock after an environment publication failure", async () => {
		const fixture = await fixtureConfig();
		const failure = new Error("environment disk unavailable");

		await expect(
			startDevDaemon(
				{ cwd: fixture.project, port: 0 },
				{
					loadConfig: async () => fixture.config,
					writeEnvironment: async () => {
						throw failure;
					},
				},
			),
		).rejects.toBe(failure);

		const paths = storagePaths(fixture.storage);
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
	});

	it("settles a failed bind before releasing the lock and preserves the created dev manifest", async () => {
		const fixture = await fixtureConfig();
		const occupied = await occupyLoopbackPort();
		try {
			await expect(
				startDevDaemon(
					{ cwd: fixture.project, port: occupied.port },
					{ loadConfig: async () => fixture.config },
				),
			).rejects.toThrow();
		} finally {
			await closeServer(occupied.server);
		}

		const paths = storagePaths(fixture.storage);
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
	});

	it("releases the acquired lock when runtime composition itself fails", async () => {
		const fixture = await fixtureConfig();
		const failure = new Error("composition failed");

		await expect(
			startDevDaemon(
				{ cwd: fixture.project, port: 0 },
				{
					createRuntime: () => {
						throw failure;
					},
					loadConfig: async () => fixture.config,
				},
			),
		).rejects.toBe(failure);
		expect(await pathExists(storagePaths(fixture.storage).lock)).toBe(false);
	});

	it("prepares persisted worlds once before creating dev and binding HTTP", async () => {
		const fixture = await fixtureConfig();
		const events: string[] = [];
		let persistedStarts = 0;
		const daemon = await startDevDaemon(
			{ cwd: fixture.project, port: 0 },
			{
				createRuntime(config, controlToken) {
					const runtime = createDevProjectRuntime(config, controlToken);
					const startPersisted = runtime.instances.startPersisted.bind(runtime.instances);
					vi.spyOn(runtime.instances, "startPersisted").mockImplementation(() => {
						persistedStarts += 1;
						events.push("runtime:prepare");
						return startPersisted();
					});
					const create = runtime.instances.create.bind(runtime.instances);
					vi.spyOn(runtime.instances, "create").mockImplementation((options) => {
						events.push("instance:create");
						return create(options);
					});
					const startServer = runtime.server.start.bind(runtime.server);
					vi.spyOn(runtime.server, "start").mockImplementation((options) => {
						events.push("http:start");
						return startServer(options);
					});
					return runtime;
				},
				loadConfig: async () => fixture.config,
			},
		);
		daemons.push(daemon);

		expect(events).toEqual(["runtime:prepare", "instance:create", "http:start"]);
		expect(persistedStarts).toBe(1);
	});

	it("does not create dev or bind HTTP when runtime preparation fails", async () => {
		const fixture = await fixtureConfig();
		const failure = new Error("persisted runtime failed");
		let createCalls = 0;
		let bindCalls = 0;

		await expect(
			startDevDaemon(
				{ cwd: fixture.project, port: 0 },
				{
					createRuntime(config, controlToken) {
						const runtime = createDevProjectRuntime(config, controlToken);
						vi.spyOn(runtime.instances, "startPersisted").mockRejectedValue(failure);
						const create = runtime.instances.create.bind(runtime.instances);
						vi.spyOn(runtime.instances, "create").mockImplementation((options) => {
							createCalls += 1;
							return create(options);
						});
						const startServer = runtime.server.start.bind(runtime.server);
						vi.spyOn(runtime.server, "start").mockImplementation((options) => {
							bindCalls += 1;
							return startServer(options);
						});
						return runtime;
					},
					loadConfig: async () => fixture.config,
				},
			),
		).rejects.toBe(failure);

		expect(createCalls).toBe(0);
		expect(bindCalls).toBe(0);
		expect(await pathExists(storagePaths(fixture.storage).lock)).toBe(false);
	});

	it("retains the storage lock through publication removal and runtime settlement", async () => {
		const fixture = await fixtureConfig();
		const events: string[] = [];
		let lockPresentDuringRemoval = false;
		let lockPresentAfterRuntimeSettlement = false;
		const daemon = await startDevDaemon(
			{ cwd: fixture.project, port: 0 },
			{
				async acquireLock(paths) {
					const lock = await acquireStorageLock(paths);
					const release = lock.release.bind(lock);
					vi.spyOn(lock, "release").mockImplementation(async () => {
						events.push("lock:release");
						await release();
					});
					return lock;
				},
				createActiveRuntimeOwner(storageRoot) {
					const owner = new ActiveRuntimeFileStore(storageRoot);
					return {
						publish: (descriptor, token) => owner.publish(descriptor, token),
						async remove(ownerId) {
							lockPresentDuringRemoval = await pathExists(storagePaths(storageRoot).lock);
							events.push("runtime-files:remove");
							return owner.remove(ownerId);
						},
					};
				},
				createRuntime(config, controlToken) {
					const runtime = createDevProjectRuntime(config, controlToken);
					const settled = runtime.server.settled.bind(runtime.server);
					vi.spyOn(runtime.server, "settled").mockImplementation(async () => {
						await settled();
						lockPresentAfterRuntimeSettlement = await pathExists(
							storagePaths(config.storage.dir).lock,
						);
						events.push("runtime:settled");
					});
					return runtime;
				},
				loadConfig: async () => fixture.config,
			},
		);
		daemons.push(daemon);

		await daemon.close();

		expect(events).toEqual(["runtime-files:remove", "runtime:settled", "lock:release"]);
		expect(lockPresentDuringRemoval).toBe(true);
		expect(lockPresentAfterRuntimeSettlement).toBe(true);
	});
});

async function fixtureConfig(): Promise<
	Readonly<{
		config: ResolvedConfig;
		project: string;
		storage: string;
	}>
> {
	const project = await mkdtemp(join(tmpdir(), "localhost2137-dev-daemon-"));
	temporaryDirectories.push(project);
	const storage = join(project, ".localhost2137");
	const config = resolveConfig(
		{ services: {}, storage: { dir: storage } },
		join(project, "localhost.config.ts"),
	);
	return Object.freeze({ config, project, storage });
}

async function occupyLoopbackPort(): Promise<Readonly<{ port: number; server: Server }>> {
	const server = createServer();
	await new Promise<void>((resolve, reject) => {
		server.once("error", reject);
		server.listen({ host: "127.0.0.1", port: 0 }, () => {
			server.removeListener("error", reject);
			resolve();
		});
	});
	const address = server.address();
	if (!address || typeof address === "string") throw new Error("Expected a TCP port.");
	return Object.freeze({ port: address.port, server });
}

async function closeServer(server: Server): Promise<void> {
	await new Promise<void>((resolve, reject) => {
		server.close((cause) => (cause ? reject(cause) : resolve()));
	});
}

async function pathExists(path: string): Promise<boolean> {
	try {
		await access(path);
		return true;
	} catch (cause) {
		if (hasCode(cause, "ENOENT")) return false;
		throw cause;
	}
}

function hasCode(value: unknown, expected: string): boolean {
	return (
		typeof value === "object" &&
		value !== null &&
		"code" in value &&
		Reflect.get(value, "code") === expected
	);
}
