import { access, mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { createServer, type Server } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { type ResolvedConfig, resolveConfig } from "../../src/config/config-resolution.js";
import { discoverActiveRuntime } from "../../src/node/active-runtime-discovery.js";
import { type DevDaemon, startDevDaemon } from "../../src/node/dev-daemon.js";
import { storagePaths } from "../../src/node/storage-paths.js";

const temporaryDirectories: string[] = [];
const daemons: DevDaemon[] = [];

afterEach(async () => {
	await Promise.all(daemons.splice(0).map((daemon) => daemon.close().catch(() => undefined)));
	await Promise.all(
		temporaryDirectories
			.splice(0)
			.map((directory) => rm(directory, { force: true, recursive: true })),
	);
});

describe("dev daemon", () => {
	it("boots a real ProjectRuntime, publishes discovery last, and leaves persistent state", async () => {
		const fixture = await fixtureConfig();
		const daemon = await startDevDaemon(
			{ cwd: fixture.project, port: 0 },
			{ loadConfig: async () => fixture.config },
		);
		daemons.push(daemon);
		const paths = storagePaths(fixture.storage);

		expect(daemon.address.port).toBeGreaterThan(0);
		expect(daemon.address.url).toBe(daemon.descriptor.url);
		expect(daemon.descriptor.configFingerprint).toBe(fixture.config.fingerprint);
		expect(daemon.connections).toEqual({ env: {}, services: {} });
		expect(daemon.environmentPath).toBe(join(fixture.storage, ".env"));
		expect(await readFile(daemon.environmentPath, "utf8")).toBe(
			"# Generated by localhost2137. Do not edit.\n",
		);
		expect((await stat(paths.controlToken)).mode & 0o777).toBe(0o600);
		expect((await stat(paths.runtime)).mode & 0o777).toBe(0o600);

		const discovered = await discoverActiveRuntime(fixture.storage);
		await expect(discovered.client.listInstances()).resolves.toEqual([
			expect.objectContaining({ id: "dev", persistence: "persistent" }),
		]);

		await daemon.close();
		await expect(daemon.close()).resolves.toBeUndefined();
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
		expect(await pathExists(daemon.environmentPath)).toBe(true);
	});

	it("rolls back the runtime and lock after an environment publication failure", async () => {
		const fixture = await fixtureConfig();
		const failure = new Error("environment disk unavailable");

		await expect(
			startDevDaemon(
				{ cwd: fixture.project, port: 0 },
				{
					loadConfig: async () => fixture.config,
					writeEnvironment: async () => {
						throw failure;
					},
				},
			),
		).rejects.toBe(failure);

		const paths = storagePaths(fixture.storage);
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
	});

	it("settles a failed bind before releasing the lock and preserves the created dev manifest", async () => {
		const fixture = await fixtureConfig();
		const occupied = await occupyLoopbackPort();
		try {
			await expect(
				startDevDaemon(
					{ cwd: fixture.project, port: occupied.port },
					{ loadConfig: async () => fixture.config },
				),
			).rejects.toThrow();
		} finally {
			await closeServer(occupied.server);
		}

		const paths = storagePaths(fixture.storage);
		expect(await pathExists(paths.runtime)).toBe(false);
		expect(await pathExists(paths.controlToken)).toBe(false);
		expect(await pathExists(paths.lock)).toBe(false);
		expect(await pathExists(join(paths.instances, "dev", "instance.json"))).toBe(true);
	});

	it("releases the acquired lock when runtime composition itself fails", async () => {
		const fixture = await fixtureConfig();
		const failure = new Error("composition failed");

		await expect(
			startDevDaemon(
				{ cwd: fixture.project, port: 0 },
				{
					createRuntime: () => {
						throw failure;
					},
					loadConfig: async () => fixture.config,
				},
			),
		).rejects.toBe(failure);
		expect(await pathExists(storagePaths(fixture.storage).lock)).toBe(false);
	});
});

async function fixtureConfig(): Promise<
	Readonly<{
		config: ResolvedConfig;
		project: string;
		storage: string;
	}>
> {
	const project = await mkdtemp(join(tmpdir(), "localhost2137-dev-daemon-"));
	temporaryDirectories.push(project);
	const storage = join(project, ".localhost2137");
	const config = resolveConfig(
		{ services: {}, storage: { dir: storage } },
		join(project, "localhost.config.ts"),
	);
	return Object.freeze({ config, project, storage });
}

async function occupyLoopbackPort(): Promise<Readonly<{ port: number; server: Server }>> {
	const server = createServer();
	await new Promise<void>((resolve, reject) => {
		server.once("error", reject);
		server.listen({ host: "127.0.0.1", port: 0 }, () => {
			server.removeListener("error", reject);
			resolve();
		});
	});
	const address = server.address();
	if (!address || typeof address === "string") throw new Error("Expected a TCP port.");
	return Object.freeze({ port: address.port, server });
}

async function closeServer(server: Server): Promise<void> {
	await new Promise<void>((resolve, reject) => {
		server.close((cause) => (cause ? reject(cause) : resolve()));
	});
}

async function pathExists(path: string): Promise<boolean> {
	try {
		await access(path);
		return true;
	} catch (cause) {
		if (hasCode(cause, "ENOENT")) return false;
		throw cause;
	}
}

function hasCode(value: unknown, expected: string): boolean {
	return (
		typeof value === "object" &&
		value !== null &&
		"code" in value &&
		Reflect.get(value, "code") === expected
	);
}
