import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { writeGeneratedDevEnvironment } from "../../src/node/generated-environment-file.js";

const temporaryDirectories: string[] = [];

afterEach(async () => {
	await Promise.all(
		temporaryDirectories
			.splice(0)
			.map((directory) => rm(directory, { force: true, recursive: true })),
	);
});

describe("generated dev environment file", () => {
	it("atomically owns only the storage-root .env", async () => {
		const project = await mkdtemp(join(tmpdir(), "localhost2137-env-file-"));
		temporaryDirectories.push(project);
		const storage = join(project, ".localhost2137");
		const userEnvironment = join(project, ".env");
		await writeFile(userEnvironment, "USER_OWNED=yes\n", "utf8");

		const generated = await writeGeneratedDevEnvironment(storage, {
			SERVICE_URL: "http://127.0.0.1:2137/dev/service",
		});
		await writeGeneratedDevEnvironment(storage, { REPLACED: "yes" });

		expect(generated).toBe(join(storage, ".env"));
		expect(await readFile(userEnvironment, "utf8")).toBe("USER_OWNED=yes\n");
		expect(await readFile(generated, "utf8")).toBe(
			'# Generated by localhost2137. Do not edit.\nREPLACED="yes"\n',
		);
		if (process.platform !== "win32") {
			expect((await stat(generated)).mode & 0o777).toBe(0o600);
		}
	});
});
