packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"
  - "examples/*"

allowBuilds:
  better-sqlite3: true
  esbuild: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@localhost2137/*"
