import { describe, expect, it } from "vitest";
import {
	renderEnvironment,
	renderGeneratedDevEnvironment,
} from "../../src/config/environment-rendering.js";

describe("environment rendering", () => {
	it("renders stable JSON and shell-safe dotenv values", () => {
		const environment = {
			Z_EMPTY: "",
			A_COMPLEX: 'line one\nquoted="yes" # $literal',
		};

		expect(renderEnvironment(environment, "dotenv")).toBe(
			'A_COMPLEX="line one\\nquoted=\\"yes\\" # $literal"\nZ_EMPTY=""\n',
		);
		expect(JSON.parse(renderEnvironment(environment, "json"))).toEqual({
			A_COMPLEX: 'line one\nquoted="yes" # $literal',
			Z_EMPTY: "",
		});
		expect(renderGeneratedDevEnvironment({})).toBe("# Generated by localhost2137. Do not edit.\n");
	});
});
