const GENERATED_ENV_HEADER = "# Generated by localhost2137. Do not edit.";

export type EnvironmentFormat = "dotenv" | "json";

export function renderEnvironment(
	environment: Readonly<Record<string, string>>,
	format: EnvironmentFormat,
): string {
	const entries = Object.entries(environment).sort(([left], [right]) => codeUnitOrder(left, right));
	if (format === "json") {
		return `${JSON.stringify(Object.fromEntries(entries), undefined, 2)}\n`;
	}
	return `${entries.map(([name, value]) => `${name}=${JSON.stringify(value)}`).join("\n")}${
		entries.length === 0 ? "" : "\n"
	}`;
}

export function renderGeneratedDevEnvironment(
	environment: Readonly<Record<string, string>>,
): string {
	return `${GENERATED_ENV_HEADER}\n${renderEnvironment(environment, "dotenv")}`;
}

function codeUnitOrder(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}
